version: '3.6'

services:
  compress-image:
    container_name: compress-image
    build: .
    env_file:
      - .env
    volumes:
      - $HOME/.aws/:/root/.aws/
    ports:
      - '9000:8080'
    env_file:
      - .env
