name: DeployLamdaFunctions

on:
    push:
        branches:
            - bun913/ec2_auto_start
    workflow_dispatch:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        env:
          WORK_DIR: ./aws_ec2_start
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: main
            - uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - run: |
                export AWS_ROLE_ARN=${{ secrets.ROLE_ARN }}
                export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
                export AWS_DEFAULT_REGION=ap-northeast-1
                echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
                echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
                echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV
            - run: |
                pip3 install -r requirements.txt -t ./src/
                zip -r package.zip ./src
              working-directory: ${{ env.WORK_DIR }}
            - run: |
                pip3 install awscli
                aws lambda update-function-code --function-name aws_ec2_start --zip-file fileb://package.zip --publish
              working-directory: ${{ env.WORK_DIR }}
